### PR TITLE
handling out of range issues better

### PR DESCRIPTION
**Pull request by schultzjim**
added guard statement and return last character if out of range, not sure if that is the desired behavior or not though. let me know

### CODE REVIEW

**Comment by cezarywojcik** [comment]
I think that it's fine the way it is. The behavior should be consistent with the behavior of an array. If you access an array out of range, you will crash. Returning the last character when accessing out of bounds might prevent noticing a bug in the future.

**Comment by schultzjim** [comment]
Cool, makes sense to me, I had the same thoughts too.

**Comment by schultzjim** [comment]
what do you think on this one, i added the limits, but maybe its better to have consistent behavior. i wonder if maybe this could implement the new `throw` `catch` behavior?

``` swift
subscript (r: Range<Int>) -> String {
    return String(self.characters[Range(start: self.startIndex.advancedBy(r.startIndex, limit: self.endIndex),
             end: self.startIndex.advancedBy(r.endIndex, limit: self.endIndex))])
}
```

**Comment by cezarywojcik** [comment]
I considered `throw`/`catch`, but that would mean that every time you use a subscript, you have to put `try` in front of the call, which could get annoying.

Do you have a specific example of why it's important to handle this? All code should be written such that an out of bounds exception doesn't happen, just the same as with arrays. I think that following the pattern set by arrays (crash on out of bounds) is best practice.

**Comment by schultzjim** [comment]
nah, i actually agree with you. just wanted to make sure i understood correctly.

**Comment by cezarywojcik** [comment]
👍
- Cezary Wojcik

Dnia Dec 4, 2015 o godz. 12:58 PM Jim Schultz notifications@github.com napisał(a):

> nah, i actually agree with you. just wanted to make sure i understood correctly.
>

**Pull request closed without merging**
